archive/flask_server/app/users/models.py
"""
Database models for users.
"""
from sqlalchemy_utils import EncryptedType

from app import db
from config import ADMINS, SECRET_KEY


class User(db.Model):
    """
    Database model representing a user.
    """
    __tablename__ = 'users_user'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True)
    password = db.Column(EncryptedType(db.String(120), SECRET_KEY))
    # TODO: Email verification

    def __init__(self, email, password):
        self.email = email
        self.password = password

    @property
    def dict(self):
        return {
            'id': self.id,
            'email': self.email,
            'password': self.password
        }

    def __repr__(self):
        return '<User {email}>'.format(email=self.email)

    @staticmethod
    def is_admin(user):
        return user is not None and user.email in ADMINS

archive/flask_server/app/users/forms.py
"""
WTForm forms for users.
"""
from flask.ext.wtf import Form, RecaptchaField
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo


class LoginForm(Form):
    """
    Form for authenticating.
    """
    email = StringField(
        label='Email',
        validators=[DataRequired(), Email()])

    password = PasswordField(
        label='Password',
        validators=[DataRequired()])


class RegisterForm(Form):
    """
    Form for creating new Users.
    """
    email = StringField(
        label='Email',
        validators=[DataRequired(), Email()])

    password = PasswordField(
        label='Password',
        validators=[DataRequired()])

    confirm = PasswordField(
        label='Repeat Password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match')
        ])

    recaptcha = RecaptchaField()

archive/flask_server/app/foo/routes.py
import json

from flask import Blueprint, render_template, request
from sqlalchemy.exc import IntegrityError

from app import db
from app.foo.forms import CreateFooForm
from app.foo.models import Foo
from app.users.decorators import requires_login


mod = Blueprint('foo', __name__, url_prefix='/foo')


@mod.route('/', methods=['GET', 'POST'])
@requires_login()
def foobar():
    """
    Page for viewing and creating Foos with form (handled on POST).
    """
    form = CreateFooForm(request.form)
    if not form.validate_on_submit():
        if form.is_submitted():
            # Validation failed
            # flash('Failed to create foo!', 'error')
            pass

        return render_template('foo/foo.html', form=form)

    # POST - Create a new Foo
    foo = Foo(
        number=form.number.data,
        text=form.text.data,
        boolean=form.boolean.data)

    try:
        # Add new Foo to the database
        db.session.add(foo)
        db.session.commit()

    except IntegrityError:
        # Failure while adding to the database
        # flash('Failed to create foo!', 'error')
        return render_template('foo/foo.html', form=form)

    # Success!
    # flash('Created a new foo!', 'success')
    return json.dumps(foo.dict)


@mod.route('/<int:foo_id>', methods=['GET'])
@requires_login()
def get(foo_id):
    """
    Retrieves a jsonified Foo instance with the given id (primary key).
    """
    # Get the Foo from the database
    foo = Foo.query.get(foo_id)

    # Convert to json
    return json.dumps(foo.dict)


@mod.route('/<int:foo_id>', methods=['DELETE'])
@requires_login()
def delete(foo_id):
    """
    Removes a Foo instance with the given id (primary key) from the database.
    """
    # Get the Foo from the database
    foo = Foo.query.get(foo_id)

    # Remove the foo from the database
    db.session.delete(foo)
    db.session.commit()

    # Convert to json
    return json.dumps(foo.dict)


@mod.route('/fetch/', methods=['GET'])
@requires_login()
def fetch():
    """
    Retrieves all Foo instances.
    """
    # Get all Foos from the database
    foos = Foo.query.all()

    # Append the Foos as dictionaries
    resources = []
    for foo in foos:
        resources.append(foo.dict)

    # Convert to json
    return json.dumps(resources)

archive/flask_server/app/users/__init__.py
"""
Module for all user resources.
"""

archive/flask_server/app/users/routes.py
"""
HTTP route handlers for the users module.
"""
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for)
from sqlalchemy.exc import IntegrityError
from werkzeug.security import check_password_hash, generate_password_hash

from app import db
from app.users.forms import LoginForm, RegisterForm
from app.users.models import User
from app.users.decorators import requires_login


# Initialize the module blueprint
mod = Blueprint('users', __name__, url_prefix='/users')


def _validate_login_form(form):
    """
    Validates a LoginForm and assigns the user to the session if successful.
    """
    # Make sure the form is submitted
    if not form.is_submitted():
        return False

    # Run WTForm validators
    if not form.validate():
        for field, errors in form.errors.iteritems():
            for error in errors:
                flash(error, 'error')

        return False

    # Validate the user credentials
    user = User.query.filter_by(email=form.email.data).first()
    if not (user and check_password_hash(
            user.password, form.password.data)):
        flash('Invalid email or password', 'error')
        return False

    # Assign the user to the session
    session['user_id'] = user.id
    flash('Welcome to the test server!')
    return True


def _validate_register_form(form):
    """
    Validates a RegisterForm and creates the user and assigns it to the session
    if successful.
    """
    # Make sure the form is submitted
    if not form.is_submitted():
        return False

    # Run WTForm validators
    if not form.validate():
        for field, errors in form.errors.iteritems():
            for error in errors:
                flash(error, 'error')

        return False

    # Create a new user
    user = User(
        email=form.email.data,
        password=generate_password_hash(form.password.data))

    # Add the user to the database
    try:
        db.session.add(user)
        db.session.commit()

    except IntegrityError:
        flash('Failed to register new user!', 'error')
        return False

    # Assign the user to the session
    session['user_id'] = user.id
    flash('Thanks for registering!', 'success')
    return True


@mod.route('/profile/')
@requires_login()
def home():
    """
    User profile page.
    """
    return render_template('users/profile.html', user=g.user)


@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """
    Login page with form (handled on POST).
    """
    form = LoginForm(request.form)
    if request.method == 'POST' and _validate_login_form(form):
        return redirect(url_for('users.home'))

    return render_template(
        'users/login.html',
        form=form,
        is_admin=User.is_admin(g.user))


@mod.route('/logout/')
def logout():
    """
    Un-assigns the user from the session and redirects to the login page.
    """
    session['user_id'] = None
    return redirect(url_for('users.login'))


@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """
    Registration page with form (handled on POST).
    """
    form = RegisterForm(request.form)
    if request.method == 'POST' and _validate_register_form(form):
        return redirect(url_for('users.home'))

    return render_template(
        'users/register.html',
        form=form,
        is_admin=User.is_admin(g.user))

archive/flask_server/app/templates/users/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <div class="container">
        {% from "forms/macros.html" import render_field %}
        <form method="POST" action="" class="form-auth">
            {{ form.csrf_token }}
            <h2>Please sign in</h2>
            <div class="form-fields">
                {{ render_field(form.email, placeholder='Email', autofocus=true) }}
                {{ render_field(form.password, placeholder='Password') }}
            </div>
            <button type="submit" class="btn btn-lg btn-primary btn-block">Sign in</button>
            <a href="{{ url_for('users.register') }}" class="btn btn-lg btn-default btn-block">Register</a>
        </form>
    </div>
{% endblock %}

archive/flask_server/app/templates/users/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Hello, you!</h1>
            <dl class="dl-horizontal">
                <dt>Email</dt>
                <dd>{{ user.email }}</dd>
                <dt>Password (Hashed)</dt>
                <dd>{{ user.password }}</dd>
            </dl>
            <p>
                <a class="btn btn-primary btn-lg" href="{{ url_for('users.logout') }}">Sign out</a>
                <a class="btn btn-default btn-lg" href="{{ url_for('foo.foobar') }}">Foobar</a>
            </p>
        </div>
    </div>
{% endblock %}

archive/flask_server/app/templates/users/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}
    <div class="container">
        {% from "forms/macros.html" import render_field %}
        <form method="POST" action="" class="form-auth">
            {{ form.csrf_token }}
            <h2>Create a new account</h2>
            <div class="form-fields">
                {{ render_field(form.email, placeholder='Email', autofocus=true) }}
                {{ render_field(form.password, placeholder='Password') }}
                {{ render_field(form.confirm, placeholder='Confirm Password') }}
                <h5>ReCaptcha</h5>
                {{ form.recaptcha }}
            </div>
            <button type="submit" class="btn btn-lg btn-primary btn-block">Register</button>
            <a href="{{ url_for('users.login') }}" class="btn btn-lg btn-default btn-block">Sign In</a>
        </form>
    </div>
{% endblock %}